### ISSUE TITLE
About scripts for online recognition and video captioning

### ISSUE THREAD

**Issue by RaRaRan** [mzolfaghari/ECO-efficient-video-understanding#24]
Hi ,I am very interested in your outstanding work.
But I have a problem when i run online recognition.py
I set the  model paths in online_recognition.py as : 

rgb_mean.mat: /home/ra/ECO-efficient-video-understanding-master/caffe_3d/action_matlab
deploy.prototxt: /home/ra/ECO-efficient-video-understanding-master/models_ECO_Lite/kinetics
ECO_Lite_kinetics.caffemodel:  download  from Google Drive

And i got error:
python online_recognition.py 
Setting device 0
WARNING: Logging before InitGoogleLogging() is written to STDERR
I1105 17:18:41.087724  7888 net.cpp:46] Initializing net from parameters: 
name: "ECOLite"
input: "data"
input_dim: 80
input_dim: 3
input_dim: 224
input_dim: 224
.
.
.
I1105 17:19:27.531430  7888 net.cpp:551] Collecting Learning Rate and Weight Decay.
I1105 17:19:27.531447  7888 net.cpp:300] Network initialization done.
I1105 17:19:27.531451  7888 net.cpp:301] Memory required for data: 3935844160
GLib-GIO-Message: 17:19:43.243: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
Traceback (most recent call last):
  File "online_recognition.py", line 122, in <module>
    online_predict(mean_file,model_def_file,model_file,classes_file,num_categories)
  File "online_recognition.py", line 92, in online_predict
    net.blobs['data'].data[...] = np.transpose(rgb[:,:,:,:], (3,2,1,0))
ValueError: could not broadcast input array from shape (16,3,224,224) into shape (80,3,224,224)

Did I set it wrong?
Please help me,thanks!

**Comment by RaRaRan** [comment]
solved! i set input_dim:80 to 16.
done!
